<?php

namespace ContainerT3Yo35Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Gr5k1qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Gr5k1q_' shared service.
     *
     * @return \App\Controller\PhoneRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\PhoneController::index()": the $phoneRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\PhoneRepository". Did you forget to add a use statement?');
    }
}
