<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFsTx1xe\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFsTx1xe/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFsTx1xe.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFsTx1xe\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFsTx1xe\App_KernelProdContainer([
    'container.build_hash' => 'FsTx1xe',
    'container.build_id' => '1be0e94b',
    'container.build_time' => 1592412298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFsTx1xe');
