<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSR6CN2g\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSR6CN2g/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSR6CN2g.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSR6CN2g\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSR6CN2g\App_KernelProdContainer([
    'container.build_hash' => 'SR6CN2g',
    'container.build_id' => 'cbfaae42',
    'container.build_time' => 1592419239,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSR6CN2g');
