<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api' => [[], ['_controller' => 'App\\Controller\\ApiController::index'], [], [['text', '/api']], [], []],
];
