<?php

namespace ContainerSR6CN2g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PhoneRepository' shared autowired service.
     *
     * @return \App\Repository\PhoneRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PhoneRepository'] = new \App\Repository\PhoneRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
